# Generated by Django 2.2.14 on 2021-02-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200906_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
